---

# 'time-rc.yaml'.


apiVersion: v1
kind: ReplicationController
metadata:
  name: time
  labels:
    name: time
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: time
    spec:
      containers:
      - image: vm1:5000/junio/time:1.0.0
        name: time
        env:
        - name: PORT
          value: '7002'
        ports:
        - name: time
          containerPort: 7002
