---

# 'web-svc.yaml'.


apiVersion: v1
kind: Service
metadata: 
  name: web
  labels:
    name: web
spec:
  type: NodePort
  ports:
  - name: web
    port: 7000
    protocol: TCP
  selector: 
    name: web
