---

# 'web.yaml'.


apiVersion: v1
kind: Service
metadata:
  name: "web-{{VERSION}}"
  labels:
    name: "web-{{VERSION}}"
spec:
  type: NodePort
  ports:
  - name: web
    port: 7000
    protocol: TCP
  selector:
    name: "web-{{VERSION}}"


---

apiVersion: v1
kind: ReplicationController
metadata:
  name: "web-{{VERSION}}"
  labels:
    name: "web-{{VERSION}}"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: "web-{{VERSION}}"
    spec:
      containers:
      - image: "vm1:5000/junio/web:{{IMAGEVERSION}}"
        name: "web-{{VERSION}}"
        env:
        - name: PORT
          value: '7000'
        - name: DATEENDPOINT
          value: date.default.svc.cluster.local
        - name: TIMEENDPOINT
          value: time.default.svc.cluster.local
        ports:
        - name: web
          containerPort: 7000
